name: map_address_picker
description: A simple flutter plugin for picking users location using google maps.
version: 0.3.5
homepage: https://github.com/athul-ain/map_address_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  google_maps_flutter_platform_interface: ^2.2.4
  geolocator_platform_interface: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter: